### PR TITLE
Add Events in CICD Charter

### PR DESCRIPTION
**Pull request by e-backmark-ericsson**
The charter for Events in CI/CD states the purpose and expected outcome for this workstream. It originates from this working document: https://docs.google.com/document/d/1cuaOHmrvK20WxHxHZZuLif3CW3q1ICZ_RglJRp_IAQ0

### CODE REVIEW

**Comment by e-backmark-ericsson** [comment]
We're in the middle of proposing our workstream to become a SIG, and this charter will become part of that proposal. As we don't know how quickly that will be done I just wanted to version control the charter here for now.

**Comment by afrittoli** [comment]
Thank you!

**Comment by link108** [comment]
exciting!

**Review by fdegir — APPROVED** [review]

**Comment by ravilach** [comment]
Excited! Great stuff!

**Pull request merged**
